
const Peliculas = [
    {
        titulo: "One Life",
        portada: "./Imagenes/Swiper/One_Life.jpg",
        sinopsis:"Esta es una biografia de un señor que salva nenes del ejercito alemám",
        director: "James Hawes",
        actores: ["Anthony Hopkins","Helena Bonham","Johnny Flynn","Lena Olin","Romola Garai","Alex Sharp","Jonathan Pryce"],
        trailer: "trailer",
        duracion: "110 minutos",
        categoria: "Drama",
    },
    {
        titulo: "Batman vs Superman",
        portada: "./Imagenes/Swiper/Batman_vs_Superman.jpg",
        sinopsis:"Pelicula de accion  y superheroes",
        director: "Zac Snyder",
        actores: ["Ben Affleck","Henry Cavill","Amy Adams","Jesse Eisenberg","Diane Lane","Laurence Fishburne","Jeremy Irons","Holly Hunter","Gal Gadot"],
        trailer: "trailer",
        duracion: "152 minutos",
        categoria: "Superheroes",
    },
    {
        titulo: "Toy Story",
        portada: "./Imagenes/Swiper/Toy_Story1.jpg",
        sinopsis:"Esta es una pelicula animada de Disney Pixar muy famosa, sobre la vida de los juguetes",
        director: "John Lasseter",
        actores: ["Tom Hanks","Tim Allen","Annie Potts","John Ratzenberger","Don Rickles","Wallace Shawn","Jim Varney"],
        trailer: "trailer",
        duracion: "81 minutos",
        categoria: "Dibujos animados",
    },
    {
        titulo: "Dune Part Two",
        portada: "./Imagenes/Swiper/Dune_2.jpg",
        sinopsis:"Esta es una pelicula de acción y ciencia ficción, futurista, muy relevante en el 2024",
        director: "Denis Villeneuve",
        actores: ["Timothée Chalamet","Zendaya","Rebecca Ferguson","Josh Brolin","Austin Butler","Florence Pugh","Dave Bautista","Christopher Walken","Léa Seydoux","Souheila Yacoub","Stellan Skarsgård","Charlotte Rampling","Javier Bardem"],
        trailer: "trailer",
        duracion: "165 minutos",
        categoria: "Ciencia Ficción",
    },
    {
        titulo: "Star Wars Episode I",
        portada: "./Imagenes/Swiper/Star_wars1.jpg",
        sinopsis:"Primera pelicula de la Saga, da comienzo a un futuro lejano donde humanos y otras especies deben convivir entre galaxias",
        director: "George Lucas",
        actores: ["Liam Neeson","Ewan McGregor","Natalie Portman","Jake Lloyd","Pernilla August","Ray Park","Ahmed Best","Anthony Daniels","Kenny Baker","Hugh Quarshie","Ian McDiarmid","Silas Carson","Samuel L. Jackson","Frank Oz"],
        trailer: "trailer",
        duracion: "136 minutos",
        categoria: "Ciencia Ficción",
    },
    {
        titulo: "Godzilla x Kong - The New Empire",
        portada: "./Imagenes/Swiper/Godzilla_x_Kong.jpg",
        sinopsis:"Ultima pelicula donde estos dos gigantes unen para derrotar a un enemigo muy poderoso",
        director: "Adam Wingard",
        actores: ["Rebecca Hall","Brian Tyree Henry","Dan Stevens","Kaylee Hottle","Alex Ferns","Fala Chen"],
        trailer: "trailer",
        duracion: "115 minutos",
        categoria: "Ciencia Ficción",
    },
    {
        titulo: "One Life",
        portada: "./Imagenes/Swiper/One_Life.jpg",
        director: "James Hawes",
        actores: ["Anthony Hopkins","Helena Bonham","Johnny Flynn","Lena Olin","Romola Garai","Alex Sharp","Jonathan Pryce"],
        trailer: "trailer",
        duracion: "110 minutos",
        categoria: "Drama",
    }
]

export default Peliculas;